---
- name: Edit GRUB
  hosts: nodes

  tasks:
  - name: change GRUB_CMDLINE_LINUX params
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"

  - name: reconfigure grub
    shell: grub2-mkconfig -o /boot/grub2/grub.cfg
...
