---
- name: FTP server installation and configuration
  hosts: nodes
  tasks:
  - name: install vsftpd
    yum:
      name: vsftpd
      state: installed
  
  - name: run vsftpd 
    service:
      name: vsftpd
      state: started
      enabled: yes
  
  - name: open ftp port
    firewalld:
      service: ftp
      state: enabled
      permanent: yes
...
