---
- name: check apache service status
  become: True
  become_method: sudo
  become_user: root
  hosts: nodes
  tasks:
  - name: get httpd service fact
    service_facts:

  - name: check httpd status
    debug:
      var: ansible_facts.services["httpd.service"]
...
