---
- name: copy index.html file
  become: True
  become_method: sudo
  become_user: root
  hosts: nodes
  tasks:
  - name: check if directory exists
    stat:
      path: /var/www/
    register: stat_result

  - name: copy site file
    copy:
      dest: /var/www/html/index.html
      src: index.html
    when: stat_result.stat.isdir
...
