---
- name: create group
  iam_group:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    name: devops
    managed_policy: arn:aws:iam::aws:policy/AmazonEC2FullAccess
    users: ansible
    state: present

...
