---
- name: create aws user
  iam:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    iam_type: user
    name: ansible
    groups: Admins
    access_key_state: create
    state: present

...
